SELECT USER FROM dual;

CREATE TABLE Member (
    name   VARCHAR2(20) NOT NULL,
    userid VARCHAR2(20) PRIMARY KEY,
    pwd    VARCHAR2(20) NOT NULL,
    phone  CHAR(20),
    email  VARCHAR2(20)
);

INSERT INTO Member(userid, pwd, name, phone, email)
VALUES ('hong', '1234', '홍길동', '010-1234-5678', 'hong@test.com');

INSERT INTO Member(userid, pwd, name, phone, email)
VALUES ('kim', 'abcd', '김철수', '010-9876-5432', 'kim@test.com');

COMMIT;

SELECT * FROM Member;

CREATE TABLE Reservation (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid         VARCHAR2(20) NOT NULL,
    departure      VARCHAR2(50) NOT NULL,
    arrival        VARCHAR2(50) NOT NULL,
    flight_date    DATE NOT NULL,
    flight_time    VARCHAR2(10) NOT NULL,
    flight_name    VARCHAR2(50) NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userid) REFERENCES Member(userid)
);

INSERT INTO Reservation(userid, departure, arrival, flight_date, flight_time, flight_name)
VALUES ('hong', 'Seoul', 'Tokyo', TO_DATE('2025-09-10', 'YYYY-MM-DD'), '10:00', 'KE123');

INSERT INTO Reservation(userid, departure, arrival, flight_date, flight_time, flight_name)
VALUES ('kim', 'Busan', 'Beijing', TO_DATE('2025-09-12', 'YYYY-MM-DD'), '15:00', 'OZ456');

COMMIT;

SELECT * FROM Reservation;
DELETE FROM Reservation;
DROP TABLE Reservation CASCADE CONSTRAINTS;




CREATE TABLE RESERVATION (
    RES_ID        NUMBER PRIMARY KEY,
    USER_ID       VARCHAR2(50),
    TRIP_TYPE     VARCHAR2(10), -- ONE_WAY or ROUND
    ORIGIN        VARCHAR2(10),
    DESTINATION   VARCHAR2(10),
    DEPART_DATE   DATE,
    RETURN_DATE   DATE,
    ADULT_COUNT   NUMBER,
    CHILD_COUNT   NUMBER,
    INFANT_COUNT  NUMBER,
    CREATED_AT    DATE DEFAULT SYSDATE
);
DROP SEQUENCE RESERVATION_SEQ;


CREATE SEQUENCE RESERVATION_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
